// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpyImposterBot.Database;

#nullable disable

namespace SpyImposterBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818150342_AddWordPairId")]
    partial class AddWordPairId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_player_index");

                    b.Property<bool>("HasImages")
                        .HasColumnType("boolean")
                        .HasColumnName("has_image");

                    b.Property<string>("ImageFileId")
                        .HasColumnType("text")
                        .HasColumnName("image_file_id");

                    b.Property<long>("PackId")
                        .HasColumnType("bigint")
                        .HasColumnName("pack_id");

                    b.Property<string>("PlayersData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("players_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageFileId")
                        .HasColumnType("text");

                    b.Property<long>("PackId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PairId")
                        .HasColumnType("bigint")
                        .HasColumnName("pair_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PackId = 1L,
                            Value = "Париж"
                        },
                        new
                        {
                            Id = 2L,
                            PackId = 1L,
                            Value = "Самолет"
                        },
                        new
                        {
                            Id = 3L,
                            PackId = 1L,
                            Value = "Школа"
                        },
                        new
                        {
                            Id = 4L,
                            PackId = 1L,
                            Value = "Космос"
                        },
                        new
                        {
                            Id = 5L,
                            PackId = 1L,
                            Value = "Банк"
                        },
                        new
                        {
                            Id = 6L,
                            PackId = 1L,
                            Value = "Больница"
                        },
                        new
                        {
                            Id = 7L,
                            PackId = 1L,
                            Value = "Дом престарелых"
                        },
                        new
                        {
                            Id = 8L,
                            PackId = 1L,
                            Value = "Зоопарк"
                        },
                        new
                        {
                            Id = 9L,
                            PackId = 1L,
                            Value = "Казино"
                        },
                        new
                        {
                            Id = 10L,
                            PackId = 1L,
                            Value = "Киностудия"
                        },
                        new
                        {
                            Id = 11L,
                            PackId = 1L,
                            Value = "Кладбище"
                        },
                        new
                        {
                            Id = 12L,
                            PackId = 1L,
                            Value = "Метро"
                        },
                        new
                        {
                            Id = 13L,
                            PackId = 1L,
                            Value = "Музей"
                        },
                        new
                        {
                            Id = 14L,
                            PackId = 1L,
                            Value = "Отель"
                        },
                        new
                        {
                            Id = 15L,
                            PackId = 1L,
                            Value = "Ночной клуб"
                        },
                        new
                        {
                            Id = 16L,
                            PackId = 1L,
                            Value = "Пляж"
                        },
                        new
                        {
                            Id = 17L,
                            PackId = 1L,
                            Value = "Ресторан"
                        },
                        new
                        {
                            Id = 18L,
                            PackId = 1L,
                            Value = "Свадьба"
                        },
                        new
                        {
                            Id = 19L,
                            PackId = 1L,
                            Value = "Подводная лодка"
                        },
                        new
                        {
                            Id = 20L,
                            PackId = 1L,
                            Value = "Полицейский участок"
                        },
                        new
                        {
                            Id = 21L,
                            PackId = 1L,
                            Value = "Стадион"
                        },
                        new
                        {
                            Id = 22L,
                            PackId = 1L,
                            Value = "Супермаркет"
                        },
                        new
                        {
                            Id = 23L,
                            PackId = 1L,
                            Value = "Стадион"
                        },
                        new
                        {
                            Id = 24L,
                            PackId = 1L,
                            Value = "Театр"
                        },
                        new
                        {
                            Id = 25L,
                            PackId = 1L,
                            Value = "Тюрма"
                        },
                        new
                        {
                            Id = 26L,
                            PackId = 1L,
                            Value = "Университет"
                        },
                        new
                        {
                            Id = 27L,
                            PackId = 1L,
                            Value = "Церковь"
                        },
                        new
                        {
                            Id = 28L,
                            PackId = 1L,
                            Value = "Цирк-шапито"
                        },
                        new
                        {
                            Id = 29L,
                            PackId = 1L,
                            Value = "Шахта"
                        },
                        new
                        {
                            Id = 30L,
                            PackId = 1L,
                            Value = "Компьютер"
                        },
                        new
                        {
                            Id = 31L,
                            ImageFileId = "AgACAgIAAxkBAAIEuGnxd5EmGZNV6BDjcU8V59bup4diAAKcGGsbY6CJS3v4KcybGiPCAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Ждун"
                        },
                        new
                        {
                            Id = 32L,
                            ImageFileId = "AgACAgIAAxkBAAIEvGnxeFClfZVSC9hvIudGtYL7Cl1WAAKdGGsbY6CJSx7Gm_Pz_EaPAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Орешки бигбоб"
                        },
                        new
                        {
                            Id = 33L,
                            ImageFileId = "AgACAgIAAxkBAAIEwGnxeLwKs5F8AbTBWNvI3gh-L4qUAAKeGGsbY6CJS7UbUf6rX1BIAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "67"
                        },
                        new
                        {
                            Id = 34L,
                            ImageFileId = "AgACAgIAAxkBAAIExGnxeP7Y8jMnc0X8d67RU4P35TWoAAKfGGsbY6CJS85f6AGh1UaGAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Орлица Зубарева"
                        },
                        new
                        {
                            Id = 35L,
                            ImageFileId = "AgACAgIAAxkBAAIEyGnxeT7iKOIv1GcAAYK6cvgzatTY0AACoRhrG2OgiUvfmJAcNvPnhgEAAwIAA3kAAzsE",
                            PackId = 2L,
                            Value = "Кит ты маму мав"
                        },
                        new
                        {
                            Id = 36L,
                            ImageFileId = "AgACAgIAAxkBAAIEzGnxeYJPtZS5IfSWG3iZRKSrGpO7AAKjGGsbY6CJS1rBHrK9yFpBAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Что у вас тут происходит"
                        },
                        new
                        {
                            Id = 37L,
                            ImageFileId = "AgACAgIAAxkBAAIE0GnxebQLpaJ7j9GCTlXFdOUc0riBAAKkGGsbY6CJS210Dub6A9WdAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Тетенька с красным кандибобером"
                        },
                        new
                        {
                            Id = 38L,
                            ImageFileId = "AgACAgIAAxkBAAIE1GnxefjcEOOpGtuCHFRJ3N9Pq64rAAKlGGsbY6CJSy803qjoyQtIAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Я мою посуду"
                        },
                        new
                        {
                            Id = 39L,
                            ImageFileId = "AgACAgIAAxkBAAIE2GnxejSWTYjXGQ5-gnil4RKlgRbaAAKpGGsbY6CJS_f300jBemV3AQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Я уже красный, культурно не получиться"
                        },
                        new
                        {
                            Id = 40L,
                            ImageFileId = "AgACAgIAAxkBAAIE3GnxemEmIKcKKznSietNPIw-VDFIAAKqGGsbY6CJSyBoGOJZQPZTAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Думайте"
                        },
                        new
                        {
                            Id = 41L,
                            ImageFileId = "AgACAgIAAxkBAAIE4Gnxen7Lb_89K352CfPg2OOk4KFzAAKrGGsbY6CJS-kfwzObiQJYAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Что вы делаете в моем холодильнике"
                        },
                        new
                        {
                            Id = 42L,
                            ImageFileId = "AgACAgIAAxkBAAIE5GnxeqwWSZyjAAFjHkXP4hKg8VNZDgACrBhrG2OgiUvoHr3XNnv46gEAAwIAA3kAAzsE",
                            PackId = 2L,
                            Value = "Шайлушай"
                        },
                        new
                        {
                            Id = 43L,
                            PackId = 2L,
                            Value = "Подозрения увеличись на 5%"
                        },
                        new
                        {
                            Id = 44L,
                            PackId = 2L,
                            Value = "Он тебе что, тапок порвал, пацан? ... Нет, я все склею! "
                        },
                        new
                        {
                            Id = 45L,
                            PackId = 2L,
                            Value = "Пацаны Владивостока, ГАЗ знакомиться А чето скучненько"
                        },
                        new
                        {
                            Id = 46L,
                            PackId = 2L,
                            Value = "Умный человек в очках"
                        },
                        new
                        {
                            Id = 47L,
                            ImageFileId = "AgACAgIAAxkBAAIE6GnxfFoi3rsj4sY_03VK7FFOwvTUAAKuGGsbY6CJS66IjEbqWl4xAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Сам решу"
                        },
                        new
                        {
                            Id = 48L,
                            PackId = 2L,
                            Value = "ПИЗ... ахахахххахах"
                        },
                        new
                        {
                            Id = 49L,
                            PackId = 2L,
                            Value = "52"
                        },
                        new
                        {
                            Id = 50L,
                            ImageFileId = "AgACAgIAAxkBAAIE7GnxfRESD7pszsOZRrvIO1wERwRHAAKwGGsbY6CJSyXvOGEH7yhnAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Пацан, можешь дверь открыть от подъезда"
                        },
                        new
                        {
                            Id = 51L,
                            ImageFileId = "AgACAgIAAxkBAAIE8GnxfS-wyJpIqVPJxLphvwJ3MlmwAAKxGGsbY6CJSyIi9rMjApLFAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Ой-ой собака ты куда? Ой песик"
                        },
                        new
                        {
                            Id = 52L,
                            ImageFileId = "AgACAgIAAxkBAAIFKWnzNrM_ib7ecbAbJL7ZhtWeEx9uAAJZFmsb2UeZS1Yawb-dfLLvAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Сафонов оплатить"
                        },
                        new
                        {
                            Id = 53L,
                            ImageFileId = "AgACAgIAAxkBAAIFLWnzNuKHrHgGX_LW-ritqFQUEx4SAAKYE2sbsmSZSwQfcY4HUHa-AQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Оп, пьяный, оп потом такой, оп пьяный"
                        },
                        new
                        {
                            Id = 54L,
                            ImageFileId = "AgACAgIAAxkBAAIFMWnzNxC14dxl9aezozWrzug8nsZQAAKZE2sbsmSZS-BvMj_EnhtaAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Заяц с часами"
                        },
                        new
                        {
                            Id = 55L,
                            ImageFileId = "AgACAgIAAxkBAAIFNWnzNzj1MLLz4H_PEdOVYNmjRPFXAAKaE2sbsmSZS_knAAHoPKwHEgEAAwIAA3gAAzsE",
                            PackId = 2L,
                            Value = "Повар спрашивает повара"
                        },
                        new
                        {
                            Id = 56L,
                            ImageFileId = "AgACAgIAAxkBAAIFOWnzN1kD_4Dw5NaS1_t34gABPzF-sQACnBNrG7JkmUvJZQH3h9VhCgEAAwIAA3kAAzsE",
                            PackId = 2L,
                            Value = "Арбуз арбуз привет"
                        },
                        new
                        {
                            Id = 57L,
                            ImageFileId = "AgACAgIAAxkBAAIFPWnzN3qjj5OzlbRpL0ub5vNmBOtOAAKdE2sbsmSZS0pr8sI10N--AQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Чиловый чел"
                        },
                        new
                        {
                            Id = 58L,
                            ImageFileId = "AgACAgIAAxkBAAIFQWnzN8C9njdC5sVsgcNgO3Y-hOfxAAKfE2sbsmSZS8Ty75ZiCUljAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Humstercombat"
                        },
                        new
                        {
                            Id = 59L,
                            ImageFileId = "AgACAgIAAxkBAAIFRWnzN-SrFX3MvZ6MCZqvuslIg-uZAAKgE2sbsmSZSzfaR4C98jjnAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Здесь черным по белому написано"
                        },
                        new
                        {
                            Id = 60L,
                            ImageFileId = "AgACAgIAAxkBAAIFSWnzOAvnppYC3lpLvG8c8UWibHdMAAKhE2sbsmSZS3miFhKNlblCAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "PvZ Disco Zombie"
                        },
                        new
                        {
                            Id = 61L,
                            ImageFileId = "AgACAgIAAxkBAAIFTWnzOFZVCRdhqCLYvXhRDogg1-XqAAKkE2sbsmSZS-OShZMU5c9dAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Пфф, абоюдно"
                        },
                        new
                        {
                            Id = 62L,
                            ImageFileId = "AgACAgIAAxkBAAIFUWnzOJd5Lp0jOV31mEo8W43r0H8GAAKmE2sbsmSZS2l_YIcZ8EXjAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Шоты лысый, плаки плаки"
                        },
                        new
                        {
                            Id = 63L,
                            ImageFileId = "AgACAgIAAxkBAAIFVWnzOLelwQMRrKv-CxWM1SGuKoOUAAKoE2sbsmSZS9eWUlpztwyvAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Йогурт апетишка, я сбежала от P`Didy"
                        },
                        new
                        {
                            Id = 64L,
                            ImageFileId = "AgACAgIAAxkBAAIFWWnzOOk3KIZxpCR5IFV5i2lZoAJGAAKpE2sbsmSZSzhX_vKOCJ7QAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "До слобады доеду"
                        },
                        new
                        {
                            Id = 65L,
                            ImageFileId = "AgACAgIAAxkBAAIFXWnzORMt6csmSXQ-dE0VeqieObBIAAKrE2sbsmSZSwi_rXnASk01AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Грустная песня мявмявмявмявмяв"
                        },
                        new
                        {
                            Id = 66L,
                            ImageFileId = "AgACAgIAAxkBAAIFYWnzOTCzFYnGR6XyKjTmeJChqRgtAAKsE2sbsmSZS1y6Oh5GYi-dAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Нагетсы Ковбой"
                        },
                        new
                        {
                            Id = 67L,
                            ImageFileId = "AgACAgIAAxkBAAIFZWnzOX0Xbl1jeDCGtN9umcNmgMFHAAKtE2sbsmSZS_KcSacmWVtWAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Sad humster"
                        },
                        new
                        {
                            Id = 68L,
                            ImageFileId = "AgACAgIAAxkBAAIFaWnzOcgFyOcnNXEskO45kAKv9feYAAKvE2sbsmSZS5Vv8B1UbyKIAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Sigmaboy песня"
                        },
                        new
                        {
                            Id = 69L,
                            ImageFileId = "AgACAgIAAxkBAAIFbWnzOfnGfMzbeG4W4yz9LgQ3C8xuAAKxE2sbsmSZS8fuG3QhIbxjAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Sigma"
                        },
                        new
                        {
                            Id = 70L,
                            ImageFileId = "AgACAgIAAxkBAAIFcWnzOlMr-76nAAE8z7jUecWtSo4kBQACtBNrG7JkmUs0NvVJKOTRhAEAAwIAA3gAAzsE",
                            PackId = 2L,
                            Value = "Дикий огурец"
                        },
                        new
                        {
                            Id = 71L,
                            ImageFileId = "AgACAgIAAxkBAAIFdWnzOnhaE-PV-Y8DefALRvCQln0tAAK1E2sbsmSZS7hu4_Q2Kmu3AQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Телочку на веранде оу ес"
                        },
                        new
                        {
                            Id = 72L,
                            ImageFileId = "AgACAgIAAxkBAAIFeWnzOqAoyroK9Qk1BZCczmeScFbkAAK2E2sbsmSZS4_L9-sOEFHOAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Аааа а я думала сова"
                        },
                        new
                        {
                            Id = 73L,
                            ImageFileId = "AgACAgIAAxkBAAIFfWnzOtt_PxrBcYpy6fu2ka_IOrB2AAK3E2sbsmSZS-A21CCuG1hOAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Але мужик ты норм? А.. нормано"
                        },
                        new
                        {
                            Id = 74L,
                            ImageFileId = "AgACAgIAAxkBAAIF3Gn0Jprqw6S9e2tvwP-_XXtshAsQAAIBEWsbcEKgS3ZgY8c54BtZAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Дед бомбом"
                        },
                        new
                        {
                            Id = 75L,
                            ImageFileId = "AgACAgIAAxkBAAIF4Gn0JrurpwyE02cQ2T4bcy8Yv9JaAAICEWsbcEKgS-ivyKjQrFwbAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Денчик слазиет"
                        },
                        new
                        {
                            Id = 76L,
                            ImageFileId = "AgACAgIAAxkBAAIF5Gn0JwHOl9n6p9ElaP0yVeewjBVPAAIDEWsbcEKgS0YYWt-RIXToAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Книга братан, идика сюда"
                        },
                        new
                        {
                            Id = 77L,
                            ImageFileId = "AgACAgIAAxkBAAIF6Gn0JzDtevnVBG4cg-u0OwSSXwABrgACBBFrG3BCoEspPbSlryUBXgEAAwIAA3gAAzsE",
                            PackId = 2L,
                            Value = "Это мой гриб, я его ем"
                        },
                        new
                        {
                            Id = 78L,
                            ImageFileId = "AgACAgIAAxkBAAIF7Gn0J4_gTS1vUxKE_xW5v2IIo5xIAAIGEWsbcEKgS6Tg0-prFGWQAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Веном"
                        },
                        new
                        {
                            Id = 79L,
                            ImageFileId = "AgACAgIAAxkBAAIF8Gn0J6xVnQmIOr3VVYjVHC58BhItAAIHEWsbcEKgS_kDxbauH_EqAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Я не мэстный"
                        },
                        new
                        {
                            Id = 80L,
                            ImageFileId = "AgACAgIAAxkBAAIF9Gn0J8_5EVEHegtjZnJNNgS_KsOFAAIIEWsbcEKgS-WsIlTX7_elAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Окак"
                        },
                        new
                        {
                            Id = 81L,
                            ImageFileId = "AgACAgIAAxkBAAIF-Gn0J-lNfitZ1UeQewABkntCq0_ligACCRFrG3BCoEsN9PfurvQygAEAAwIAA20AAzsE",
                            PackId = 2L,
                            Value = "Толик, это подъезд"
                        },
                        new
                        {
                            Id = 82L,
                            ImageFileId = "AgACAgIAAxkBAAIF_Gn0KASkaNmw4CTxAAGsUUZ1MRc86AACChFrG3BCoEvK9qrRqbtOVQEAAwIAA20AAzsE",
                            PackId = 2L,
                            Value = "Это фиаско братан"
                        },
                        new
                        {
                            Id = 83L,
                            ImageFileId = "AgACAgIAAxkBAAIGAAFp9ChRu1nDpdi_YdbPQQJ3t8w7hgACDBFrG3BCoEvJCjVgvrrEMgEAAwIAA20AAzsE",
                            PackId = 2L,
                            Value = "Шампунь Жумайсынба"
                        },
                        new
                        {
                            Id = 84L,
                            ImageFileId = "AgACAgIAAxkBAAIGBGn0KHAcS4Lm0zq8MVDzdpEX_-HrAAINEWsbcEKgS0Z3da2uNKXdAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Наталья морская пехота"
                        },
                        new
                        {
                            Id = 85L,
                            ImageFileId = "AgACAgIAAxkBAAIGCGn0KKMp6MggeOhWCmqORTgKrvHsAAIOEWsbcEKgS5PomOBxbp8sAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Бэн (игра)"
                        },
                        new
                        {
                            Id = 86L,
                            ImageFileId = "AgACAgIAAxkBAAIGDGn0KL1KXB5QwKdeySMcVE2HVyAUAAIPEWsbcEKgS-ZvzRFttht-AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Чимин (Брайан Мапс)"
                        },
                        new
                        {
                            Id = 87L,
                            ImageFileId = "AgACAgIAAxkBAAIGEGn0KNsaW0ogV6Z3-748IcB4b-TpAAIQEWsbcEKgSykIB8tQ8hNtAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Кчау Молния МакВин"
                        },
                        new
                        {
                            Id = 88L,
                            ImageFileId = "AgACAgIAAxkBAAIGFGn0KWJfajoLa_Umm6u7Y7aCDUPqAAITEWsbcEKgS6VW0TzgxUZkAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "ИванЗоло2004"
                        },
                        new
                        {
                            Id = 89L,
                            ImageFileId = "AgACAgIAAxkBAAIGGGn0KXrUXy4ldBEH_WTzhgM14_WQAAIUEWsbcEKgS8F_sPovg96oAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Доброе утро мопсы"
                        },
                        new
                        {
                            Id = 90L,
                            ImageFileId = "AgACAgIAAxkBAAIGHGn0KZaVwBzOVGh1DthUL__WovnRAAIVEWsbcEKgS9juZLK2da0wAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Широкий Путин"
                        },
                        new
                        {
                            Id = 91L,
                            ImageFileId = "AgACAgIAAxkBAAIGIGn0KbeEX0HLdeWorfgwEj0hQIllAAIWEWsbcEKgS9dwdoS7ry68AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "О вы из англии"
                        },
                        new
                        {
                            Id = 92L,
                            ImageFileId = "AgACAgIAAxkBAAIGJGn0Kebdc6AaIj9eJsoWvhnzPgnGAAIYEWsbcEKgS0JuyWxvcJBPAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Зачем/Почему/Man"
                        },
                        new
                        {
                            Id = 93L,
                            ImageFileId = "AgACAgIAAxkBAAIGKGn0KhLgmmyjELFfRa_x5g8nV8WGAAIZEWsbcEKgSxJpCZPQ_8iUAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Гроб (африканцы несту)"
                        },
                        new
                        {
                            Id = 94L,
                            PackId = 2L,
                            Value = "Да ну нахуй бля - забор закрыт"
                        },
                        new
                        {
                            Id = 95L,
                            ImageFileId = "AgACAgIAAxkBAAIGLGn0KlEEvalDWIVA1pO-BinuBBTCAAIaEWsbcEKgS88vztcc0U_dAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Да яж пошутил"
                        },
                        new
                        {
                            Id = 96L,
                            ImageFileId = "AgACAgIAAxkBAAIGMGn0Km_gKdTyRkb0TMa7sBzpagmuAAIbEWsbcEKgS1XIRc12cjidAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Можно, а зачем?"
                        },
                        new
                        {
                            Id = 97L,
                            ImageFileId = "AgACAgIAAxkBAAIGNGn0Ko3kYvDTQ5q74ub1TFsa97blAAIcEWsbcEKgS-WjGiFsh2lcAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Чел хорош"
                        },
                        new
                        {
                            Id = 98L,
                            ImageFileId = "AgACAgIAAxkBAAIGOGn0KqouDQbNU8dfORsOpzFomqtdAAIeEWsbcEKgSyJP3htfMrgFAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Кринж"
                        },
                        new
                        {
                            Id = 99L,
                            PackId = 2L,
                            Value = "Мем Ок Ок"
                        },
                        new
                        {
                            Id = 100L,
                            ImageFileId = "AgACAgIAAxkBAAIGPGn0Kt-LXZ34bTUiTGdMNnUZk2h_AAIfEWsbcEKgS11WlpuH-T5iAQADAgADeQADOwQ",
                            PackId = 2L,
                            Value = "Извинись"
                        },
                        new
                        {
                            Id = 101L,
                            PackId = 2L,
                            Value = "Ты большая, молодец!"
                        },
                        new
                        {
                            Id = 102L,
                            ImageFileId = "AgACAgIAAxkBAAIGQGn0KySAtIOmAieR29d9fKfeBWEVAAIjEWsbcEKgS9L0gbJKunlyAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Что самое главное в женщине? Душа"
                        },
                        new
                        {
                            Id = 103L,
                            ImageFileId = "AgACAgIAAxkBAAIGRGn0K1YgWYBKUlN6SS8oadm_2e97AAIkEWsbcEKgS4YPE0_NrmJwAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Чувак это рэпчик"
                        },
                        new
                        {
                            Id = 104L,
                            ImageFileId = "AgACAgIAAxkBAAIGSGn0K2-7iTlelFgen3DhgOjramFfAAImEWsbcEKgS3bVT8jp0xuJAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Как сказать-то"
                        },
                        new
                        {
                            Id = 105L,
                            ImageFileId = "AgACAgIAAxkBAAIGTGn0K5KysTrrugsEJsnYolqWesciAAIpEWsbcEKgS5JGHPgFvz4KAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Это печально"
                        },
                        new
                        {
                            Id = 106L,
                            ImageFileId = "AgACAgIAAxkBAAIGUGn0K6qPr4Qe5oGYTZVufzWLtzj2AAIqEWsbcEKgS9WV2Fxi2vO1AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Веселый/Веселый(перечеркнуто)"
                        },
                        new
                        {
                            Id = 107L,
                            ImageFileId = "AgACAgIAAxkBAAIGVGn0K8yMwnRDL25CscQ8SL6VTx1EAAIrEWsbcEKgS97mpGszDYn6AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "О он c%*&$@#я мем про носорога"
                        },
                        new
                        {
                            Id = 108L,
                            ImageFileId = "AgACAgIAAxkBAAIGWGn0LCR8VXj66EaPcoCMtDXwsg5aAAIsEWsbcEKgS7q3ke18LQAB4wEAAwIAA20AAzsE",
                            PackId = 2L,
                            Value = "Упал вставай, вставай упай, чокопай"
                        },
                        new
                        {
                            Id = 109L,
                            ImageFileId = "AgACAgIAAxkBAAIGXGn0LEOuTeE-OsZoRiilNFCwZ1kEAAItEWsbcEKgSyD1KZ8CFiy7AQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Мэлстрой"
                        },
                        new
                        {
                            Id = 110L,
                            ImageFileId = "AgACAgIAAxkBAAIGYGn0LGUTwH0focSWFoIikZQepohEAAIvEWsbcEKgS1Sk6VOaDMfQAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Возьми телефон детка"
                        },
                        new
                        {
                            Id = 111L,
                            ImageFileId = "AgACAgIAAxkBAAIGZGn0LH1b6K8dSwITlUoV3BegFNvUAAIwEWsbcEKgS0dDr09JalrNAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Чипсеки"
                        },
                        new
                        {
                            Id = 112L,
                            ImageFileId = "AgACAgIAAxkBAAIGaGn0LKkqXPStVGACUUKOXY5ljtYIAAIyEWsbcEKgSw5HGorvo_upAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Тише, узбеки спят"
                        },
                        new
                        {
                            Id = 113L,
                            ImageFileId = "AgACAgIAAxkBAAIGbGn0LNAQPqzhP6qh8wIQCHHxontSAAI0EWsbcEKgS3qnbr-yrkWKAQADAgADeAADOwQ",
                            PackId = 2L,
                            Value = "Мактрахер"
                        },
                        new
                        {
                            Id = 114L,
                            ImageFileId = "AgACAgIAAxkBAAIGcGn0LOyqqsOuJa4peoWfCbiLu9nvAAI2EWsbcEKgS1KrZohLyA88AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Пенсия хайпует"
                        },
                        new
                        {
                            Id = 115L,
                            ImageFileId = "AgACAgIAAxkBAAIGdGn0LQe920LZGclBnG-uffVoVcHTAAI3EWsbcEKgS-JG9SlN7C_9AQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Спидран по майнкрафту погнали"
                        },
                        new
                        {
                            Id = 116L,
                            ImageFileId = "AgACAgIAAxkBAAIGeGn0LSQxMdAVnzlCnIUg9rxPspU8AAI5EWsbcEKgS_aZn9VfgAYkAQADAgADbQADOwQ",
                            PackId = 2L,
                            Value = "Бургер Кинг говно"
                        },
                        new
                        {
                            Id = 117L,
                            ImageFileId = "AgACAgIAAxkBAAIGiGn0LiDaFrnUzFIr-nApQc5y-OzfAAI7EWsbcEKgS8fZ8yycTBZvAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Дипер"
                        },
                        new
                        {
                            Id = 118L,
                            ImageFileId = "AgACAgIAAxkBAAIGjGn0LlOizAIYAYXAm47YRklDMIKzAAI8EWsbcEKgS2Fz4BtrFrLWAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Мейбл"
                        },
                        new
                        {
                            Id = 119L,
                            ImageFileId = "AgACAgIAAxkBAAIGkGn0Lm4jTzHmWV0SyPBmM2ucZTN5AAI-EWsbcEKgSz2EzcngH5BbAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Дядя Стэн"
                        },
                        new
                        {
                            Id = 120L,
                            ImageFileId = "AgACAgIAAxkBAAIGlGn0LowoF8ARSW1jZTRC8FlgnS6EAAI_EWsbcEKgS2azdp7CLP1_AQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Венди"
                        },
                        new
                        {
                            Id = 121L,
                            ImageFileId = "AgACAgIAAxkBAAIGmGn0LruzY97VYPGvYG_bDZHhen2fAAJAEWsbcEKgS1EheKOGi9WLAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Робби"
                        },
                        new
                        {
                            Id = 122L,
                            ImageFileId = "AgACAgIAAxkBAAIGnGn0Ls8g6FfuZXtM7R8yF0GJjp2PAAJBEWsbcEKgS_fnHTTqjxMVAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Бил Шифр"
                        },
                        new
                        {
                            Id = 123L,
                            ImageFileId = "AgACAgIAAxkBAAIGoGn0LuZd5TxykGFR1yVFxHx4Z35MAAJCEWsbcEKgS1srQghAPsoXAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Блендин"
                        },
                        new
                        {
                            Id = 124L,
                            ImageFileId = "AgACAgIAAxkBAAIGpGn0LwAB269f1dyVawSYxW7P2w9vmwACQxFrG3BCoEuWpV4pTWhrOgEAAwIAA20AAzsE",
                            PackId = 3L,
                            Value = "Стэнфорд"
                        },
                        new
                        {
                            Id = 125L,
                            ImageFileId = "AgACAgIAAxkBAAIGqGn0LyoZw-k8cME9q7_mHtjbpjSeAAJFEWsbcEKgSzrbk3SpzEN-AQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Гидеон"
                        },
                        new
                        {
                            Id = 126L,
                            ImageFileId = "AgACAgIAAxkBAAIGrGn0L0KAC9NZp9tIhMwdcQM1jCXhAAJGEWsbcEKgS7lPzazhFskbAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Зус"
                        },
                        new
                        {
                            Id = 127L,
                            ImageFileId = "AgACAgIAAxkBAAIGsGn0L1i8k7osIeI0R0P2QKnm7D3FAAJHEWsbcEKgSwuTXBprOEDAAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Гренда"
                        },
                        new
                        {
                            Id = 128L,
                            ImageFileId = "AgACAgIAAxkBAAIGtGn0L2_5nt6icjFtsvPZQc00tlsuAAJJEWsbcEKgS4S-6f4TZ431AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Бабулита"
                        },
                        new
                        {
                            Id = 129L,
                            ImageFileId = "AgACAgIAAxkBAAIGuGn0L4RsnqpiER4EdxTcQ7CY6mk4AAJKEWsbcEKgS4CSLY8kAAFVgAEAAwIAA20AAzsE",
                            PackId = 3L,
                            Value = "Пасификка"
                        },
                        new
                        {
                            Id = 130L,
                            ImageFileId = "AgACAgIAAxkBAAIGvGn0L51eOSZqHx1dOsaaQ6ho1BnKAAJLEWsbcEKgSxjxr1ReRjwdAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Толстый шериф Блабс"
                        },
                        new
                        {
                            Id = 131L,
                            ImageFileId = "AgACAgIAAxkBAAIGwGn0L8ha3alJAW2mX6c43CvFhv9IAAJMEWsbcEKgS9v5ntltx-PIAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Кенди"
                        },
                        new
                        {
                            Id = 132L,
                            ImageFileId = "AgACAgIAAxkBAAIGxGn0L-PDIiQcMIJkrlCp3CRtaYx4AAJNEWsbcEKgS0JefBYVXXQeAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Худой шериф Дурланд"
                        },
                        new
                        {
                            Id = 133L,
                            ImageFileId = "AgACAgIAAxkBAAIGyGn0MAXXQTqJnnYSCDPYWW8LCf3eAAJOEWsbcEKgS-IQllR_TYLqAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Старик Макгакет"
                        },
                        new
                        {
                            Id = 134L,
                            ImageFileId = "AgACAgIAAxkBAAIGzGn0MCZlVLT430GYQ4vmRWQ3kBzCAAJPEWsbcEKgS206zpqdSORRAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Пухля"
                        },
                        new
                        {
                            Id = 135L,
                            ImageFileId = "AgACAgIAAxkBAAIG0Gn0MEFWgNPzubmNYe0SjmNSW8WjAAJQEWsbcEKgSzNIlhe59vC3AQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Козел"
                        },
                        new
                        {
                            Id = 136L,
                            ImageFileId = "AgACAgIAAxkBAAIG1Gn0MFje465KyMvBQs_brwhROFdRAAJREWsbcEKgSxdKlhOM8DGmAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Тоби решительный"
                        },
                        new
                        {
                            Id = 137L,
                            ImageFileId = "AgACAgIAAxkBAAIG2Gn0MHYDIC3YQRDA1Vyos2yFZvtpAAJSEWsbcEKgS6vNUJ2RavjVAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Русалдо"
                        },
                        new
                        {
                            Id = 138L,
                            ImageFileId = "AgACAgIAAxkBAAIG3Gn0MJxp2qdzcIC7gqUYmrR45LdJAAJTEWsbcEKgSyUq9SsPzv4KAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Гифани"
                        },
                        new
                        {
                            Id = 139L,
                            ImageFileId = "AgACAgIAAxkBAAIG4Gn0MMT3xV2oeRRu-sQjuYewDsMPAAJVEWsbcEKgSyWbKvFU9llWAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Бей его (Тайлер Кьютбайкер)"
                        },
                        new
                        {
                            Id = 140L,
                            ImageFileId = "AgACAgIAAxkBAAIG5Gn0MO8UiZVVr2FHeGJL1gU3ZVhBAAJWEWsbcEKgSzYg4hjsvJb-AQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Ленивая Сьюзан"
                        },
                        new
                        {
                            Id = 141L,
                            ImageFileId = "AgACAgIAAxkBAAIG6Gn0MQPYuaGSb8KqjLYkOOg94wE2AAJXEWsbcEKgS60W1YkZ6ZGMAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Тембри"
                        },
                        new
                        {
                            Id = 142L,
                            ImageFileId = "AgACAgIAAxkBAAIG7Gn0MSUW48Ou4Bf1OIUeSPHEeCb_AAJYEWsbcEKgS1MWKntx8eWFAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Шандра Хименес"
                        },
                        new
                        {
                            Id = 143L,
                            ImageFileId = "AgACAgIAAxkBAAIG8Gn0MT0sxdudLqTZ5OekdWWNqC1dAAJZEWsbcEKgS1X2_5nM-fNYAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Томпсон"
                        },
                        new
                        {
                            Id = 144L,
                            ImageFileId = "AgACAgIAAxkBAAIG9Gn0MVwfLBEtIEk4E1MKRyDvg6s5AAJaEWsbcEKgS7Rd5j1AUK9OAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Крамбл Макс Кернишь"
                        },
                        new
                        {
                            Id = 145L,
                            ImageFileId = "AgACAgIAAxkBAAIG-Gn0MZs4UkV3b4NY70nMV7Qh9jv1AAJbEWsbcEKgSykXsTiS_TuDAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Мультимедведь"
                        },
                        new
                        {
                            Id = 146L,
                            ImageFileId = "AgACAgIAAxkBAAIG_Gn0Mb2EeqCX0NVRoqaMcAKoZrmzAAJcEWsbcEKgS3R-J4DkfOM7AQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Мужикотавры"
                        },
                        new
                        {
                            Id = 147L,
                            ImageFileId = "AgACAgIAAxkBAAIHAAFp9DHaXHyPoWlIHjIzocOIeov8SgACYhFrG3BCoEvDeHyCD5OdEAEAAwIAA3kAAzsE",
                            PackId = 3L,
                            Value = "Малыш времени"
                        },
                        new
                        {
                            Id = 148L,
                            ImageFileId = "AgACAgIAAxkBAAIHBGn0MfSfGZXX90oYh-5KsILN4Uq2AAJkEWsbcEKgS_kagn8nlfg_AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Шмебьюлок"
                        },
                        new
                        {
                            Id = 149L,
                            ImageFileId = "AgACAgIAAxkBAAIHCGn0MhMchBvNiHHBCcsQi_GG2Jn-AAJnEWsbcEKgS62A4FyYWGvpAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Бтс"
                        },
                        new
                        {
                            Id = 150L,
                            ImageFileId = "AgACAgIAAxkBAAIHEGn0Mjmn1FglmHi-4pJ0S9WsStcbAAJpEWsbcEKgS_1ZQWu9g6TnAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Восковые статуи"
                        },
                        new
                        {
                            Id = 151L,
                            ImageFileId = "AgACAgIAAxkBAAIHFGn0MmIGXvEryhwyuUlXkzspWmGvAAJqEWsbcEKgS-weW4gp3vblAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Единороги"
                        },
                        new
                        {
                            Id = 152L,
                            ImageFileId = "AgACAgIAAxkBAAIHGGn0MofzIj_ZZXbn3y6OFF1AN7ebAAJrEWsbcEKgS03dEG--4i1nAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Агенты Пауэрс"
                        },
                        new
                        {
                            Id = 153L,
                            ImageFileId = "AgACAgIAAxkBAAIHHGn0MqgiiL59caereFRtQhaQckSlAAJsEWsbcEKgS7NyKuriWwNtAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Слепой Глазго (из культа)"
                        },
                        new
                        {
                            Id = 154L,
                            ImageFileId = "AgACAgIAAxkBAAIHIGn0Mtrfj_i9Cr-2MqfcuW67LKh2AAJuEWsbcEKgS4ubbSw9gfl0AQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Святой Валентин"
                        },
                        new
                        {
                            Id = 155L,
                            ImageFileId = "AgACAgIAAxkBAAIHJGn0M3-VCtDSk_bhJoAll8NIgZR6AAJyEWsbcEKgS_X0wNUFpsDFAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Батя Гидеона Бад"
                        },
                        new
                        {
                            Id = 156L,
                            ImageFileId = "AgACAgIAAxkBAAIHLGn0M7neY5ArKhp9hH-r1yNGYihMAAJ0EWsbcEKgS88d2d5r3-SkAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Летувинский ловкач"
                        },
                        new
                        {
                            Id = 157L,
                            ImageFileId = "AgACAgIAAxkBAAIHMGn0M8_WooxHjpuUAjqQqzA6bDiuAAJ1EWsbcEKgS8eKHI13cX50AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Ручная ведьма"
                        },
                        new
                        {
                            Id = 158L,
                            ImageFileId = "AgACAgIAAxkBAAIHOGn0M_j_pPHa2egX86WiOSACfQFTAAJ3EWsbcEKgS6rMF-zk60KtAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Циклоп пластилиновый"
                        },
                        new
                        {
                            Id = 159L,
                            ImageFileId = "AgACAgIAAxkBAAIHPGn0NGfq3ClgMmQUuPJrXuzbHNOZAAJ5EWsbcEKgSz19MVCD-qOlAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Нейт (друг Венди)"
                        },
                        new
                        {
                            Id = 160L,
                            ImageFileId = "AgACAgIAAxkBAAIHQGn0NI43ZZZ53OYmadkTeY7ELAzxAAJ6EWsbcEKgS-KcjCS0IfsqAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Ли (друг Венди)"
                        },
                        new
                        {
                            Id = 161L,
                            ImageFileId = "AgACAgIAAxkBAAIHRGn0NLynAX4U7SdRtn9ipREY2mFmAAJ7EWsbcEKgS0uYKtDOosjfAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Гигантская рука (Голова с рукой)"
                        },
                        new
                        {
                            Id = 162L,
                            ImageFileId = "AgACAgIAAxkBAAIHSGn0NN_1N3e5-kt32PBYs7kgeESxAAJ9EWsbcEKgS9sqkS0okw0TAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Арчибальд (дух лесоруб)"
                        },
                        new
                        {
                            Id = 163L,
                            ImageFileId = "AgACAgIAAxkBAAIHTGn0NQ1B9y1gm7CTzTUc0zLDaVaJAAJ_EWsbcEKgS_7JHOKxZrhGAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Тетя паук (бывшая Стэна)"
                        },
                        new
                        {
                            Id = 164L,
                            ImageFileId = "AgACAgIAAxkBAAIHUGn0NTcOYtLh2XMc5Tordm0VbGaNAAKAEWsbcEKgS4y1Y81m_vpWAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Замятыш"
                        },
                        new
                        {
                            Id = 165L,
                            ImageFileId = "AgACAgIAAxkBAAIHVGn0NWUT28sIEOdZ5viroveB4WJ9AAKCEWsbcEKgS8pZjz4njtRxAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Основатель Гравити Фолз (Квентин Трэмбли)"
                        },
                        new
                        {
                            Id = 166L,
                            ImageFileId = "AgACAgIAAxkBAAIHWGn0NYyv5CfJgZLtDepYzSOwPZbjAAKDEWsbcEKgS-zTRM-LXJbcAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Утка-тив"
                        },
                        new
                        {
                            Id = 167L,
                            ImageFileId = "AgACAgIAAxkBAAIHXGn0NcFq9Gukra1mfknVblRRGhkIAAKEEWsbcEKgS0626qiTXUC_AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Лилигольферы"
                        },
                        new
                        {
                            Id = 168L,
                            ImageFileId = "AgACAgIAAxkBAAIHZGn0NjKrNIWtTF_0Rx7GTMdpfszDAAKGEWsbcEKgS0RGJVyGk4MFAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Охраник бассейна"
                        },
                        new
                        {
                            Id = 169L,
                            ImageFileId = "AgACAgIAAxkBAAIHaGn0Nmu6k9eC7eeNgXcTD9IKNt09AAKJEWsbcEKgS4tSDcrpiO1WAQADAgADeAADOwQ",
                            PackId = 3L,
                            Value = "Заключенный бассейна"
                        },
                        new
                        {
                            Id = 170L,
                            ImageFileId = "AgACAgIAAxkBAAIHbGn0NodrXzQ5e8eLF-seiiAqi2F7AAKKEWsbcEKgSwvWxVzLCjo5AQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Тед Стрендж (брат Била)"
                        },
                        new
                        {
                            Id = 171L,
                            ImageFileId = "AgACAgIAAxkBAAIHcGn0NqSmGAs6aDyBqyP7T0bK8QikAAKLEWsbcEKgS60vY16GJgpHAQADAgADeQADOwQAgACAgIAAxkBAAIHcGn0NqSmGAs6aDyBqyP7T0bK8QikAAKLEWsbcEKgS60vY16GJgpHAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Рэджм (Брат Зуса)"
                        },
                        new
                        {
                            Id = 172L,
                            ImageFileId = "AgACAgIAAxkBAAIHdGn0NtI33pU439zLnBHKGQVyPwjXAAKMEWsbcEKgS53xPEl8VkJ4AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Монстр который умеет перевоплощаться"
                        },
                        new
                        {
                            Id = 173L,
                            ImageFileId = "AgACAgIAAxkBAAIHeGn0NxRJ0-uXLkV1-GX1DB0EFNSwAAKOEWsbcEKgSxmk82OdFCN3AQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Монстр из заставки, на 1ом кадре"
                        },
                        new
                        {
                            Id = 174L,
                            ImageFileId = "AgACAgIAAxkBAAIHfGn0Nzgn2zBuU0R18O1emiD16BQTAAKPEWsbcEKgS8ddiA3y-CVHAQADAgADeQADOwQ",
                            PackId = 3L,
                            Value = "Мирный жител, чувак с пиццей на футболке"
                        },
                        new
                        {
                            Id = 175L,
                            PackId = 3L,
                            Value = "Дипер кртуой"
                        },
                        new
                        {
                            Id = 176L,
                            ImageFileId = "AgACAgIAAxkBAAIHgGn0N2kH9TP-EiPqeDolzGkLmuO3AAKQEWsbcEKgS6WM1Lwoz-4JAQADAgADbQADOwQ",
                            PackId = 3L,
                            Value = "Судья кот из мира Мейбл"
                        },
                        new
                        {
                            Id = 177L,
                            ImageFileId = "AgACAgIAAxkBAAIHhGn0N8Ouvj9c83V28TVlAAGNBTWCvQACkRFrG3BCoEua0LSnMgKHuQEAAwIAA3gAAzsE",
                            PackId = 3L,
                            Value = "Норман"
                        },
                        new
                        {
                            Id = 178L,
                            PackId = 4L,
                            PairId = 1L,
                            Value = "Кошка"
                        },
                        new
                        {
                            Id = 179L,
                            PackId = 4L,
                            PairId = 1L,
                            Value = "Собака"
                        },
                        new
                        {
                            Id = 180L,
                            PackId = 4L,
                            PairId = 2L,
                            Value = "Чай"
                        },
                        new
                        {
                            Id = 181L,
                            PackId = 4L,
                            PairId = 2L,
                            Value = "Кофе"
                        },
                        new
                        {
                            Id = 182L,
                            PackId = 4L,
                            PairId = 3L,
                            Value = "Море"
                        },
                        new
                        {
                            Id = 183L,
                            PackId = 4L,
                            PairId = 3L,
                            Value = "Океан"
                        },
                        new
                        {
                            Id = 184L,
                            PackId = 4L,
                            PairId = 4L,
                            Value = "Самолет"
                        },
                        new
                        {
                            Id = 185L,
                            PackId = 4L,
                            PairId = 4L,
                            Value = "Вертолет"
                        },
                        new
                        {
                            Id = 186L,
                            PackId = 4L,
                            PairId = 5L,
                            Value = "Зима"
                        },
                        new
                        {
                            Id = 187L,
                            PackId = 4L,
                            PairId = 5L,
                            Value = "Лето"
                        },
                        new
                        {
                            Id = 188L,
                            PackId = 4L,
                            PairId = 6L,
                            Value = "Книга"
                        },
                        new
                        {
                            Id = 189L,
                            PackId = 4L,
                            PairId = 6L,
                            Value = "Журнал"
                        },
                        new
                        {
                            Id = 190L,
                            PackId = 4L,
                            PairId = 7L,
                            Value = "Кино"
                        },
                        new
                        {
                            Id = 191L,
                            PackId = 4L,
                            PairId = 7L,
                            Value = "Сериал"
                        },
                        new
                        {
                            Id = 192L,
                            PackId = 4L,
                            PairId = 8L,
                            Value = "Врач"
                        },
                        new
                        {
                            Id = 193L,
                            PackId = 4L,
                            PairId = 8L,
                            Value = "Медсестра"
                        },
                        new
                        {
                            Id = 194L,
                            PackId = 4L,
                            PairId = 9L,
                            Value = "Пицца"
                        },
                        new
                        {
                            Id = 195L,
                            PackId = 4L,
                            PairId = 9L,
                            Value = "Бургер"
                        },
                        new
                        {
                            Id = 196L,
                            PackId = 4L,
                            PairId = 10L,
                            Value = "Лев"
                        },
                        new
                        {
                            Id = 197L,
                            PackId = 4L,
                            PairId = 10L,
                            Value = "Тигр"
                        });
                });

            modelBuilder.Entity("WordPack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("HasImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpyImageFileId")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("word_packs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            HasImage = false,
                            IsPublic = true,
                            Name = "Классика"
                        },
                        new
                        {
                            Id = 2L,
                            HasImage = true,
                            IsPublic = true,
                            Name = "Мемы",
                            SpyImageFileId = "AgACAgIAAxkBAAIDcWnqFF73-ck3yCkIGaC-ILiGbz8vAAIfE2sbeT1ZS65DyBa6QXhIAQADAgADeQADOwQ"
                        },
                        new
                        {
                            Id = 3L,
                            HasImage = true,
                            IsPublic = true,
                            Name = "Гравити Фолз",
                            SpyImageFileId = "AgACAgIAAxkBAAIDcWnqFF73-ck3yCkIGaC-ILiGbz8vAAIfE2sbeT1ZS65DyBa6QXhIAQADAgADeQADOwQ"
                        },
                        new
                        {
                            Id = 4L,
                            HasImage = false,
                            IsPublic = true,
                            Name = "Парные слова"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
