// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpyImposterBot.Database;

#nullable disable

namespace SpyImposterBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423120029_refactoringValueWords")]
    partial class refactoringValueWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_player_index");

                    b.Property<bool>("HasImages")
                        .HasColumnType("boolean")
                        .HasColumnName("has_image");

                    b.Property<string>("ImageFileId")
                        .HasColumnType("text")
                        .HasColumnName("image_file_id");

                    b.Property<long>("PackId")
                        .HasColumnType("bigint")
                        .HasColumnName("pack_id");

                    b.Property<string>("PlayersData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("players_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ImageFileId")
                        .HasColumnType("text");

                    b.Property<long>("PackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PackId = 1L,
                            Value = "Париж"
                        },
                        new
                        {
                            Id = 2L,
                            PackId = 1L,
                            Value = "Самолет"
                        },
                        new
                        {
                            Id = 3L,
                            PackId = 1L,
                            Value = "Школа"
                        },
                        new
                        {
                            Id = 4L,
                            PackId = 1L,
                            Value = "Космос"
                        },
                        new
                        {
                            Id = 5L,
                            PackId = 1L,
                            Value = "Банк"
                        },
                        new
                        {
                            Id = 6L,
                            PackId = 1L,
                            Value = "Больница"
                        },
                        new
                        {
                            Id = 7L,
                            PackId = 1L,
                            Value = "Дом престарелых"
                        },
                        new
                        {
                            Id = 8L,
                            PackId = 1L,
                            Value = "Зоопарк"
                        },
                        new
                        {
                            Id = 9L,
                            PackId = 1L,
                            Value = "Казино"
                        },
                        new
                        {
                            Id = 10L,
                            PackId = 1L,
                            Value = "Киностудия"
                        },
                        new
                        {
                            Id = 11L,
                            PackId = 1L,
                            Value = "Кладбище"
                        },
                        new
                        {
                            Id = 12L,
                            PackId = 1L,
                            Value = "Метро"
                        },
                        new
                        {
                            Id = 13L,
                            PackId = 1L,
                            Value = "Музей"
                        },
                        new
                        {
                            Id = 14L,
                            PackId = 1L,
                            Value = "Отель"
                        },
                        new
                        {
                            Id = 15L,
                            PackId = 1L,
                            Value = "Ночной клуб"
                        },
                        new
                        {
                            Id = 16L,
                            PackId = 1L,
                            Value = "Пляж"
                        },
                        new
                        {
                            Id = 17L,
                            PackId = 1L,
                            Value = "Ресторан"
                        },
                        new
                        {
                            Id = 18L,
                            PackId = 1L,
                            Value = "Свадьба"
                        },
                        new
                        {
                            Id = 19L,
                            PackId = 1L,
                            Value = "Подводная лодка"
                        },
                        new
                        {
                            Id = 20L,
                            PackId = 1L,
                            Value = "Полицейский участок"
                        },
                        new
                        {
                            Id = 21L,
                            PackId = 1L,
                            Value = "Стадион"
                        },
                        new
                        {
                            Id = 22L,
                            PackId = 1L,
                            Value = "Супермаркет"
                        },
                        new
                        {
                            Id = 23L,
                            PackId = 1L,
                            Value = "Стадион"
                        },
                        new
                        {
                            Id = 24L,
                            PackId = 1L,
                            Value = "Театр"
                        },
                        new
                        {
                            Id = 25L,
                            PackId = 1L,
                            Value = "Тюрма"
                        },
                        new
                        {
                            Id = 26L,
                            PackId = 1L,
                            Value = "Университет"
                        },
                        new
                        {
                            Id = 27L,
                            PackId = 1L,
                            Value = "Церковь"
                        },
                        new
                        {
                            Id = 28L,
                            PackId = 1L,
                            Value = "Цирк-шапито"
                        },
                        new
                        {
                            Id = 29L,
                            PackId = 1L,
                            Value = "Шахта"
                        },
                        new
                        {
                            Id = 30L,
                            PackId = 1L,
                            Value = "Компьютер"
                        },
                        new
                        {
                            Id = 31L,
                            PackId = 2L,
                            Value = "Ждун"
                        },
                        new
                        {
                            Id = 32L,
                            PackId = 2L,
                            Value = "Орешки бигбоб"
                        },
                        new
                        {
                            Id = 33L,
                            PackId = 2L,
                            Value = "67"
                        },
                        new
                        {
                            Id = 34L,
                            PackId = 2L,
                            Value = "Орлица Зубарева"
                        },
                        new
                        {
                            Id = 35L,
                            PackId = 2L,
                            Value = "Кит ты маму мав"
                        },
                        new
                        {
                            Id = 36L,
                            PackId = 2L,
                            Value = "Что у вас тут происходит"
                        },
                        new
                        {
                            Id = 37L,
                            PackId = 2L,
                            Value = "Тетенька с красным кандибобером"
                        },
                        new
                        {
                            Id = 38L,
                            PackId = 2L,
                            Value = "Я мою посуду, я мою посуду"
                        },
                        new
                        {
                            Id = 39L,
                            PackId = 2L,
                            Value = "Я уже красный"
                        },
                        new
                        {
                            Id = 40L,
                            PackId = 2L,
                            Value = "Думайте"
                        },
                        new
                        {
                            Id = 41L,
                            PackId = 2L,
                            Value = "Что вы делаете в моем холодильнике"
                        },
                        new
                        {
                            Id = 42L,
                            PackId = 2L,
                            Value = "Шайлушай"
                        },
                        new
                        {
                            Id = 43L,
                            PackId = 2L,
                            Value = "Подозрения увеличись на 5%"
                        },
                        new
                        {
                            Id = 44L,
                            PackId = 2L,
                            Value = "Пацан он тебе тапок разорвал... я все склею"
                        },
                        new
                        {
                            Id = 45L,
                            PackId = 2L,
                            Value = "Пацаны Владивостока. ГАЗ знакомиться"
                        },
                        new
                        {
                            Id = 46L,
                            PackId = 2L,
                            Value = "Умный человек в очках"
                        },
                        new
                        {
                            Id = 47L,
                            PackId = 2L,
                            Value = "Сам решу"
                        },
                        new
                        {
                            Id = 48L,
                            PackId = 2L,
                            Value = "ПИЗ... ахахахххахах"
                        },
                        new
                        {
                            Id = 49L,
                            PackId = 2L,
                            Value = "52"
                        },
                        new
                        {
                            Id = 50L,
                            PackId = 2L,
                            Value = "Пацан, можешь дверь открыть от подъезда"
                        },
                        new
                        {
                            Id = 51L,
                            PackId = 2L,
                            Value = "Ой-ой собака ты куда? Ой песик"
                        },
                        new
                        {
                            Id = 52L,
                            PackId = 2L,
                            Value = "Сафонов оплатить"
                        },
                        new
                        {
                            Id = 53L,
                            PackId = 2L,
                            Value = "Оп, пьяный, оп потом такой, оп пьяный"
                        },
                        new
                        {
                            Id = 54L,
                            PackId = 2L,
                            Value = "Заяц с часами"
                        },
                        new
                        {
                            Id = 55L,
                            PackId = 2L,
                            Value = "Повар спрашивает повара"
                        },
                        new
                        {
                            Id = 56L,
                            PackId = 2L,
                            Value = "Арбуз арбуз привет"
                        },
                        new
                        {
                            Id = 57L,
                            PackId = 2L,
                            Value = "Чиловый чел"
                        },
                        new
                        {
                            Id = 58L,
                            PackId = 2L,
                            Value = "Humstercombat"
                        },
                        new
                        {
                            Id = 59L,
                            PackId = 2L,
                            Value = "Здесь черным по белому написано"
                        },
                        new
                        {
                            Id = 60L,
                            PackId = 2L,
                            Value = "PvZ Disco Zombie"
                        },
                        new
                        {
                            Id = 61L,
                            PackId = 2L,
                            Value = "Пфф, абоюдно"
                        },
                        new
                        {
                            Id = 62L,
                            PackId = 2L,
                            Value = "Шоты лысый, плаки плаки"
                        },
                        new
                        {
                            Id = 63L,
                            PackId = 2L,
                            Value = "Йогурт апетишка, я сбежала от P`Didy"
                        },
                        new
                        {
                            Id = 64L,
                            PackId = 2L,
                            Value = "До слобады доеду"
                        },
                        new
                        {
                            Id = 65L,
                            PackId = 2L,
                            Value = "Грустная песня мявмявмявмявмяв"
                        },
                        new
                        {
                            Id = 66L,
                            PackId = 2L,
                            Value = "Нагетсы Ковбой"
                        },
                        new
                        {
                            Id = 67L,
                            PackId = 2L,
                            Value = "Sad humster"
                        },
                        new
                        {
                            Id = 68L,
                            PackId = 2L,
                            Value = "Sigmaboy песня"
                        },
                        new
                        {
                            Id = 69L,
                            PackId = 2L,
                            Value = "Sigms"
                        },
                        new
                        {
                            Id = 70L,
                            PackId = 2L,
                            Value = "Дикий огурец"
                        },
                        new
                        {
                            Id = 71L,
                            PackId = 2L,
                            Value = "Телочку на веранде оу ес"
                        },
                        new
                        {
                            Id = 72L,
                            PackId = 2L,
                            Value = "Аааа а я думала сова"
                        },
                        new
                        {
                            Id = 73L,
                            PackId = 2L,
                            Value = "Але мужик ты норм? А.. нормано"
                        },
                        new
                        {
                            Id = 74L,
                            PackId = 2L,
                            Value = "Дед бомбом"
                        },
                        new
                        {
                            Id = 75L,
                            PackId = 2L,
                            Value = "Денчик слазиет"
                        },
                        new
                        {
                            Id = 76L,
                            PackId = 2L,
                            Value = "Книга братан, идика сюда"
                        },
                        new
                        {
                            Id = 77L,
                            PackId = 2L,
                            Value = "Это мой гриб, я его ем"
                        },
                        new
                        {
                            Id = 78L,
                            PackId = 2L,
                            Value = "Веном"
                        },
                        new
                        {
                            Id = 79L,
                            PackId = 2L,
                            Value = "Я не мэстный"
                        },
                        new
                        {
                            Id = 80L,
                            PackId = 2L,
                            Value = "Окак"
                        },
                        new
                        {
                            Id = 81L,
                            PackId = 2L,
                            Value = "Толик, это подъезд"
                        },
                        new
                        {
                            Id = 82L,
                            PackId = 2L,
                            Value = "Это фиаско братан"
                        },
                        new
                        {
                            Id = 83L,
                            PackId = 2L,
                            Value = "Шампунь Жумайсонба"
                        },
                        new
                        {
                            Id = 84L,
                            PackId = 2L,
                            Value = "Наталья морская пехота"
                        },
                        new
                        {
                            Id = 85L,
                            PackId = 2L,
                            Value = "Бэн (игра)"
                        },
                        new
                        {
                            Id = 86L,
                            PackId = 2L,
                            Value = "Чимин (Брайан Мапс)"
                        },
                        new
                        {
                            Id = 87L,
                            PackId = 2L,
                            Value = "Кчау Молния МакВин"
                        },
                        new
                        {
                            Id = 88L,
                            PackId = 2L,
                            Value = "ИванЗоло2004"
                        },
                        new
                        {
                            Id = 89L,
                            PackId = 2L,
                            Value = "Доброе утро мопсы"
                        },
                        new
                        {
                            Id = 90L,
                            PackId = 2L,
                            Value = "Широкий Путин"
                        },
                        new
                        {
                            Id = 91L,
                            PackId = 2L,
                            Value = "О вы из англии"
                        },
                        new
                        {
                            Id = 92L,
                            PackId = 2L,
                            Value = "Зачем? (лощадь у моря)"
                        },
                        new
                        {
                            Id = 93L,
                            PackId = 2L,
                            Value = "Гроб (африканцы несту)"
                        },
                        new
                        {
                            Id = 94L,
                            PackId = 2L,
                            Value = "Да ну нахуй бля - забор закрыт"
                        },
                        new
                        {
                            Id = 95L,
                            PackId = 2L,
                            Value = "Да яж пошутил"
                        },
                        new
                        {
                            Id = 96L,
                            PackId = 2L,
                            Value = "Можно, а зачем?"
                        },
                        new
                        {
                            Id = 97L,
                            PackId = 2L,
                            Value = "Чел хорош"
                        },
                        new
                        {
                            Id = 98L,
                            PackId = 2L,
                            Value = "Кринж"
                        },
                        new
                        {
                            Id = 99L,
                            PackId = 2L,
                            Value = "Мем Ок Ок"
                        },
                        new
                        {
                            Id = 100L,
                            PackId = 2L,
                            Value = "Извинись"
                        },
                        new
                        {
                            Id = 101L,
                            PackId = 2L,
                            Value = "Ты большая, молодец!"
                        },
                        new
                        {
                            Id = 102L,
                            PackId = 2L,
                            Value = "Что самое главное в женщине? Душа"
                        },
                        new
                        {
                            Id = 103L,
                            PackId = 2L,
                            Value = "Чувак это рэпчик"
                        },
                        new
                        {
                            Id = 104L,
                            PackId = 2L,
                            Value = "Как сказать-то"
                        },
                        new
                        {
                            Id = 105L,
                            PackId = 2L,
                            Value = "Это печально"
                        },
                        new
                        {
                            Id = 106L,
                            PackId = 2L,
                            Value = "Веселый/Веселый(перечеркнуто)"
                        },
                        new
                        {
                            Id = 107L,
                            PackId = 2L,
                            Value = "О он съебался мем про носорога"
                        },
                        new
                        {
                            Id = 108L,
                            PackId = 2L,
                            Value = "Упал вставай, вставай упай, чокопай"
                        },
                        new
                        {
                            Id = 109L,
                            PackId = 2L,
                            Value = "Мэлстрой"
                        },
                        new
                        {
                            Id = 110L,
                            PackId = 2L,
                            Value = "Возьми телефон детка"
                        },
                        new
                        {
                            Id = 111L,
                            PackId = 2L,
                            Value = "Чипсеки"
                        },
                        new
                        {
                            Id = 112L,
                            PackId = 2L,
                            Value = "Тише, узбеки спят"
                        },
                        new
                        {
                            Id = 113L,
                            PackId = 2L,
                            Value = "Мактрахер"
                        },
                        new
                        {
                            Id = 114L,
                            PackId = 2L,
                            Value = "Пенсия хайпует"
                        },
                        new
                        {
                            Id = 115L,
                            PackId = 2L,
                            Value = "Спидран по майнкрафту погнали"
                        },
                        new
                        {
                            Id = 116L,
                            PackId = 2L,
                            Value = "Бургер Кинг говно"
                        },
                        new
                        {
                            Id = 117L,
                            PackId = 3L,
                            Value = "Дипер"
                        },
                        new
                        {
                            Id = 118L,
                            PackId = 3L,
                            Value = "Мейбл"
                        },
                        new
                        {
                            Id = 119L,
                            PackId = 3L,
                            Value = "Дядя Стен"
                        },
                        new
                        {
                            Id = 120L,
                            PackId = 3L,
                            Value = "Венди"
                        },
                        new
                        {
                            Id = 121L,
                            PackId = 3L,
                            Value = "Робин"
                        },
                        new
                        {
                            Id = 122L,
                            PackId = 3L,
                            Value = "Бил Шифр"
                        },
                        new
                        {
                            Id = 123L,
                            PackId = 3L,
                            Value = "Блендин"
                        },
                        new
                        {
                            Id = 124L,
                            PackId = 3L,
                            Value = "Стенфорд"
                        },
                        new
                        {
                            Id = 125L,
                            PackId = 3L,
                            Value = "Гидеон"
                        },
                        new
                        {
                            Id = 126L,
                            PackId = 3L,
                            Value = "Зус"
                        },
                        new
                        {
                            Id = 127L,
                            PackId = 3L,
                            Value = "Гренда"
                        },
                        new
                        {
                            Id = 128L,
                            PackId = 3L,
                            Value = "Бабулита"
                        },
                        new
                        {
                            Id = 129L,
                            PackId = 3L,
                            Value = "Пасификка"
                        },
                        new
                        {
                            Id = 130L,
                            PackId = 3L,
                            Value = "Толстый шериф Плапс"
                        },
                        new
                        {
                            Id = 131L,
                            PackId = 3L,
                            Value = "Кенди"
                        },
                        new
                        {
                            Id = 132L,
                            PackId = 3L,
                            Value = "Худой шериф Дурланд"
                        },
                        new
                        {
                            Id = 133L,
                            PackId = 3L,
                            Value = "Старик Макгакет"
                        },
                        new
                        {
                            Id = 134L,
                            PackId = 3L,
                            Value = "Пухля"
                        },
                        new
                        {
                            Id = 135L,
                            PackId = 3L,
                            Value = "Козел"
                        },
                        new
                        {
                            Id = 136L,
                            PackId = 3L,
                            Value = "Тоби решительный"
                        },
                        new
                        {
                            Id = 137L,
                            PackId = 3L,
                            Value = "Русалдо"
                        },
                        new
                        {
                            Id = 138L,
                            PackId = 3L,
                            Value = "Гифани"
                        },
                        new
                        {
                            Id = 139L,
                            PackId = 3L,
                            Value = "Бей его"
                        },
                        new
                        {
                            Id = 140L,
                            PackId = 3L,
                            Value = "Тетя из кафе Сьзан"
                        },
                        new
                        {
                            Id = 141L,
                            PackId = 3L,
                            Value = "Тембри"
                        },
                        new
                        {
                            Id = 142L,
                            PackId = 3L,
                            Value = "Шандра Хименес"
                        },
                        new
                        {
                            Id = 143L,
                            PackId = 3L,
                            Value = "Томпсон"
                        },
                        new
                        {
                            Id = 144L,
                            PackId = 3L,
                            Value = "Крамбл Макс Кернишь"
                        },
                        new
                        {
                            Id = 145L,
                            PackId = 3L,
                            Value = "Мультимедведь"
                        },
                        new
                        {
                            Id = 146L,
                            PackId = 3L,
                            Value = "Мужикотавр"
                        },
                        new
                        {
                            Id = 147L,
                            PackId = 3L,
                            Value = "Малыш времени"
                        },
                        new
                        {
                            Id = 148L,
                            PackId = 3L,
                            Value = "Шмебьюлок"
                        },
                        new
                        {
                            Id = 149L,
                            PackId = 3L,
                            Value = "Бтс"
                        },
                        new
                        {
                            Id = 150L,
                            PackId = 3L,
                            Value = "Восковые статуи"
                        },
                        new
                        {
                            Id = 151L,
                            PackId = 3L,
                            Value = "Единорожки"
                        },
                        new
                        {
                            Id = 152L,
                            PackId = 3L,
                            Value = "Агенты ФБР Пауэрс (черные волосы)"
                        },
                        new
                        {
                            Id = 153L,
                            PackId = 3L,
                            Value = "Слепой Глазго (из культа)"
                        },
                        new
                        {
                            Id = 154L,
                            PackId = 3L,
                            Value = "Святой Валентин"
                        },
                        new
                        {
                            Id = 155L,
                            PackId = 3L,
                            Value = "Батя Гидеона Бад"
                        },
                        new
                        {
                            Id = 156L,
                            PackId = 3L,
                            Value = "Летувинский ловкач"
                        },
                        new
                        {
                            Id = 157L,
                            PackId = 3L,
                            Value = "Ручная ведьма"
                        },
                        new
                        {
                            Id = 158L,
                            PackId = 3L,
                            Value = "Циклоп пластилиновый"
                        },
                        new
                        {
                            Id = 159L,
                            PackId = 3L,
                            Value = "Татуированный друг Венди"
                        },
                        new
                        {
                            Id = 160L,
                            PackId = 3L,
                            Value = "Блондин (друг Венди)"
                        },
                        new
                        {
                            Id = 161L,
                            PackId = 3L,
                            Value = "Гигантская рука (Голова с рукой)"
                        },
                        new
                        {
                            Id = 162L,
                            PackId = 3L,
                            Value = "Арчибальд (дух лесоруб)"
                        },
                        new
                        {
                            Id = 163L,
                            PackId = 3L,
                            Value = "Тетя паук (бывшая Стена)"
                        },
                        new
                        {
                            Id = 164L,
                            PackId = 3L,
                            Value = "Замятыш (клон Дипера)"
                        },
                        new
                        {
                            Id = 165L,
                            PackId = 3L,
                            Value = "Основатель Гравити Фолз"
                        },
                        new
                        {
                            Id = 166L,
                            PackId = 3L,
                            Value = "Утка Холмс"
                        },
                        new
                        {
                            Id = 167L,
                            PackId = 3L,
                            Value = "Лилигоферы"
                        },
                        new
                        {
                            Id = 168L,
                            PackId = 3L,
                            Value = "Охраник бассейна"
                        },
                        new
                        {
                            Id = 169L,
                            PackId = 3L,
                            Value = "Заключенный бассейна"
                        },
                        new
                        {
                            Id = 170L,
                            PackId = 3L,
                            Value = "Тед Стрендж (брат Била)"
                        },
                        new
                        {
                            Id = 171L,
                            PackId = 3L,
                            Value = "Брат Зуса"
                        },
                        new
                        {
                            Id = 172L,
                            PackId = 3L,
                            Value = "Монстр который умеет перевоплощаться"
                        },
                        new
                        {
                            Id = 173L,
                            PackId = 3L,
                            Value = "Монстр из заставки, на 1ом кадре"
                        },
                        new
                        {
                            Id = 174L,
                            PackId = 3L,
                            Value = "Мирный жител, чувак с пиццей на футболке"
                        },
                        new
                        {
                            Id = 175L,
                            PackId = 3L,
                            Value = "Дипер кртуой"
                        },
                        new
                        {
                            Id = 176L,
                            PackId = 3L,
                            Value = "Судья кот из мира Мейбл"
                        });
                });

            modelBuilder.Entity("WordPack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("HasImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpyImageFileId")
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("word_packs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            HasImage = false,
                            IsPublic = true,
                            Name = "Классика"
                        },
                        new
                        {
                            Id = 2L,
                            HasImage = true,
                            IsPublic = true,
                            Name = "Мемы"
                        },
                        new
                        {
                            Id = 3L,
                            HasImage = true,
                            IsPublic = true,
                            Name = "Гравити Фолз"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
