// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpyImposterBot.Database;

#nullable disable

namespace SpyImposterBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422042511_changeGameSessionAndAddWordPacks")]
    partial class changeGameSessionAndAddWordPacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_player_index");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_mode");

                    b.Property<long>("PackId")
                        .HasColumnType("bigint")
                        .HasColumnName("pack_id");

                    b.Property<string>("PlayersData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("players_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("PackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.ToTable("words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PackId = 1L,
                            Value = "Париж"
                        },
                        new
                        {
                            Id = 2L,
                            PackId = 1L,
                            Value = "Самолет"
                        },
                        new
                        {
                            Id = 3L,
                            PackId = 1L,
                            Value = "Школа"
                        },
                        new
                        {
                            Id = 4L,
                            PackId = 1L,
                            Value = "Космос"
                        },
                        new
                        {
                            Id = 5L,
                            PackId = 1L,
                            Value = "Компьютер"
                        },
                        new
                        {
                            Id = 6L,
                            PackId = 2L,
                            Value = "Ждун"
                        },
                        new
                        {
                            Id = 7L,
                            PackId = 2L,
                            Value = "Чел хорош"
                        },
                        new
                        {
                            Id = 8L,
                            PackId = 2L,
                            Value = "Кринж"
                        });
                });

            modelBuilder.Entity("WordPack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("word_packs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsPublic = true,
                            Name = "Классика"
                        },
                        new
                        {
                            Id = 2L,
                            IsPublic = true,
                            Name = "Мемы"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
